title: pona.la
description: >-
  lipu tomo pi lipu 'pona.la'
url: "https://pona.la/"

lawa:
- nimi: github
  linluwi: https://github.com/pona-la
- nimi: o pali e lipu sina
  linluwi: /request

# Build settings
remote_theme: pona-la/kule-lipu
